### PR TITLE
Added proxy to python client and java client

### PR DESCRIPTION
**Pull request by tryptichon**
* Added proxy to python client.
* Python client version 2.3.1
* Java client version 2.2.6-SNAPSHOT
* Refactoring

### CODE REVIEW

**Comment by mglusiuk** [comment]
and who need this proxy?
proxy is bad. it usually requires credentials or special certs handling. proxy is bad...

**Comment by tryptichon** [comment]
See Zendesk Ticket 7618 / Story #175512739
In short: Mahle needs it. It's for a on-premise connector.

**Review by SteffenBauer — APPROVED** [review]
From the Python side it looks straightforward, no objections there so far from me.

**Comment by tryptichon** [comment]
I'll wait until Miroslav gives his approval as well. At the moment we are unsure whether we want to have proxies here at all.

**Review by mglusiuk — APPROVED** [review]

**Pull request merged**
